---
- name: Deploy HTML Code
  hosts: localhost
  become: yes  # Enable privilege escalation
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: Build and Deploy Docker Container
      shell: |
        docker build -t html-app .
        docker run -d --name html-container -p 80:80 html-app
