---
- name: Deploy HTML Code
  hosts: localhost
  become: yes
  tasks:
    # Ensure Docker is installed
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    # Start Docker service
    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    # Stop and remove any existing Docker container
    - name: Stop and Remove Existing Container
      shell: |
        docker stop html-container || true
        docker rm html-container || true

    # Build Docker image from the Dockerfile
    - name: Build Docker Image
      shell: docker build -t html-app .

    # Run Docker container
    - name: Run Docker Container
      shell: docker run -d --name html-container -p 80:80 html-app

    # Verify Docker container is running
    - name: Verify Container Running
      shell: docker ps -q -f name=html-container
      register: container_status
      failed_when: container_status.stdout == ""
